# Generated by Django 6.0.6 on 2026-06-23 05:28

import movies.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, validators=[movies.validators.validate_youtube_url]),
        ),
    ]
